name: Latest book list from a goodreads
on:
  schedule: # Run workflow automatically
    # This will make it run every hour
    - cron: "0 6,18 * * *"
    # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch:
jobs:
  update-readme-with-goodreads-books:
    name: Update this repo's README with goodreads books
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # what you're currently reading
      - uses: zwacky/goodreads-profile-workflow@v1.2.2
        with:
          goodreads_user_id: "110145002"
          shelf: "currently-reading"
